---
title: "Practice Activity 8 Rowe"
author: "Joshua Rowe"
format: 
  html: 
    self-contained: true
editor: visual
---

## Setup

```{r Setup}
#| message: false
#| warning: false

library(tidyverse)
library(glue)
library(stringr)
library(english)

xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")

xmas_small <- slice_head(xmas, n = 2)

```

## Step 1

Question 1.

```{r Step1}

pluralize_gift <- function(gift) {
  stopifnot(is.character(gift))
  
  gift <- gift |> 
    str_c("s", sep = "") |> 
    str_replace("ys$", "ies") |> 
    str_replace("ooses", "eese")
  
  return(gift)
}

# Test pluralize_gift function:
pluralize_gift(xmas_small$Gift.Item)

```

## Step 2

Question 2.

```{r Step2}

make_phrase <- function(num_word, item, verb, adjective, location) {
  
  stopifnot(is.character(num_word) | is.character(item) | is.character(verb) | 
              is.character(adjective) | is.character(location))
  
  item <- if_else(num_word == "one", 
                  item, 
                  pluralize_gift(item))
  
  phrase <- glue("{num_word}", "{adjective}", "{item}", "{verb}", 
                   "{location}", .sep = " ")
    
  phrase <- str_remove_all(phrase, "NA")
  phrase <- str_squish(phrase)
    
  return(phrase)
  
}

# Test make_phrase function:
make_phrase(num_word = "ten", 
            item = "lord", 
            verb = "a-leaping", 
            adjective = NA, 
            location = NA)

```

## Step 3

Question 3.

```{r}

xmas <- xmas |> 
  mutate(day.num = english(seq(xmas$Day.in.Words)), 
         day.num = as.character(day.num),
    Full.Phrase = pmap_chr(.l = list(num_word = day.num, 
                                  item = Gift.Item, 
                                  verb = Verb, 
                                  adjective = Adjective, 
                                  location = Location), 
                           .f = make_phrase)
  )

```
